In [1]:
import pandas as pd

In [2]:
import seaborn as sns
import missingno as msno 

In [3]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class   
0         0       3    male  22.0      1      0   7.2500        S  Third  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
df.embark_town.describe()

count             889
unique              3
top       Southampton
freq              644
Name: embark_town, dtype: object

In [7]:
df.embark_town.unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [8]:
df.deck.dtypes

CategoricalDtype(categories=['A', 'B', 'C', 'D', 'E', 'F', 'G'], ordered=False)

In [9]:
df.deck.unique()

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [10]:
df.deck.describe()

count     203
unique      7
top         C
freq       59
Name: deck, dtype: object

In [11]:
df = df.select_dtypes(["int64","float64"])

In [12]:
df.head()

survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [13]:
from ycimpute.imputer import knnimput

modele sokmak için array haline getirmeli ve daha sonrasında eklenen verilerle birlikte dataframe e çevrileceği için kolon isimlerini almalıyız

In [14]:
var_names = list(df)

In [15]:
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [16]:
import numpy as np

In [17]:
np_arr = np.array(df)

In [18]:
np_arr

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

## KNN algoritmasıyla tahmin doldurma

In [19]:
dff = knnimput.KNN(k = 4).complete(np_arr)

Imputing row 1/891 with 0 missing, elapsed time: 0.065
Imputing row 101/891 with 0 missing, elapsed time: 0.067
Imputing row 201/891 with 0 missing, elapsed time: 0.067
Imputing row 301/891 with 1 missing, elapsed time: 0.067
Imputing row 401/891 with 0 missing, elapsed time: 0.068
Imputing row 501/891 with 0 missing, elapsed time: 0.068
Imputing row 601/891 with 0 missing, elapsed time: 0.068
Imputing row 701/891 with 0 missing, elapsed time: 0.068
Imputing row 801/891 with 0 missing, elapsed time: 0.069


eksik değerler tahmine dayalı dolduruldu. Simdi dataframe e çevireceğiz 

In [20]:
df = pd.DataFrame(dff,columns=var_names)

In [21]:
df.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

## random forest algoritmasıyla tahmin doldurma 

In [22]:
df = sns.load_dataset("titanic")
df.head()
df = df.select_dtypes(["int64","float64"])

In [23]:
df.head()

survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [24]:
from ycimpute.imputer import iterforest
dff = iterforest.IterImput().complete(np_arr)

AttributeError: module 'ycimpute.imputer.iterforest' has no attribute 'IterImput'

In [ ]:
!pip install ycimpute==0.1.1

In [25]:
dff = pd.DataFrame(dff,columns=var_names)

In [26]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

# Standardizasyon

In [27]:
import pandas as pd 
import numpy as np

In [28]:
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame({"V1":V1,"V2":V2,"V3":V3})

In [29]:
df

V1  V2  V3
0   1   7   6
1   3   7  12
2   6   5   5
3   5   8   6
4   7  12  14

In [30]:
df = df.astype(float)

In [31]:
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

## Standardizasyon

### standartlaştırmanın amaçı değişken değerlerinin ortalamasını 0 standart sapmasını 1 yapacak şekilde standartlaştırılmasıdır diyebiliriz

In [33]:
from sklearn import preprocessing

In [34]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

## Normalizasyon

### Burada ise değerler 0 ile 1 arasında ölçeklendirilir

In [35]:
preprocessing.normalize(df)## 0 ile 1 arasına alıyor

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max Dönüşümü

### min max ise değerleri girilen aralıkta ölçeklendirilir

In [37]:
scaler=preprocessing.MinMaxScaler(feature_range=(10,20))# verilen iki aralık arasında dönüştürme yapar
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

# Değişken Dönüşümleri

In [39]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [40]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

## 0-1 Dönüşümü

In [41]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [42]:
lbe.fit_transform(df.sex)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [44]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [51]:
df["yeni_cinsiyet"] = lbe.fit_transform(df.sex)

In [52]:
df

total_bill   tip     sex smoker   day    time  size  yeni_cinsiyet
0         16.99  1.01  Female     No   Sun  Dinner     2              0
1         10.34  1.66    Male     No   Sun  Dinner     3              1
2         21.01  3.50    Male     No   Sun  Dinner     3              1
3         23.68  3.31    Male     No   Sun  Dinner     2              1
4         24.59  3.61  Female     No   Sun  Dinner     4              0
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3              1
240       27.18  2.00  Female    Yes   Sat  Dinner     2              0
241       22.67  2.00    Male    Yes   Sat  Dinner     2              1
242       17.82  1.75    Male     No   Sat  Dinner     2              1
243       18.78  3.00  Female     No  Thur  Dinner     2              0

[244 rows x 8 columns]

## 1 ve Diğerleri(0) Dönüşümü

In [53]:
import numpy as np

In [54]:
df["yeni_day"] = np.where(df["day"].str.contains("Sun"),1,0)

In [55]:
df

total_bill   tip     sex smoker   day    time  size  yeni_cinsiyet   
0         16.99  1.01  Female     No   Sun  Dinner     2              0  \
1         10.34  1.66    Male     No   Sun  Dinner     3              1   
2         21.01  3.50    Male     No   Sun  Dinner     3              1   
3         23.68  3.31    Male     No   Sun  Dinner     2              1   
4         24.59  3.61  Female     No   Sun  Dinner     4              0   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              1   
240       27.18  2.00  Female    Yes   Sat  Dinner     2              0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2              1   
242       17.82  1.75    Male     No   Sat  Dinner     2              1   
243       18.78  3.00  Female     No  Thur  Dinner     2              0   

     yeni_day  
0           1  
1           1  
2           1  
3           1  
4           1  
..        ...  
239         0  
240         0  
241         0  
242         0  
243         0  

[244 rows x 9 columns]

## Çok sınıflı Dönüşüm

In [56]:
lbe = LabelEncoder()

In [58]:
lbe.fit_transform(df.day)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [59]:
df

total_bill   tip     sex smoker   day    time  size  yeni_cinsiyet   
0         16.99  1.01  Female     No   Sun  Dinner     2              0  \
1         10.34  1.66    Male     No   Sun  Dinner     3              1   
2         21.01  3.50    Male     No   Sun  Dinner     3              1   
3         23.68  3.31    Male     No   Sun  Dinner     2              1   
4         24.59  3.61  Female     No   Sun  Dinner     4              0   
..          ...   ...     ...    ...   ...     ...   ...            ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              1   
240       27.18  2.00  Female    Yes   Sat  Dinner     2              0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2              1   
242       17.82  1.75    Male     No   Sat  Dinner     2              1   
243       18.78  3.00  Female     No  Thur  Dinner     2              0   

     yeni_day  
0           1  
1           1  
2           1  
3           1  
4           1  
..        ...  
239         0  
240         0  
241         0  
242         0  
243         0  

[244 rows x 9 columns]

### Çok Önemli!! Yukarıda yaptığımız gibi çok kategorili değişkeni dönüştürdüğümüzde bize 0,1,2,3  değerleini döndürdü . Burada bir sıkıntı yok . Kategor,ik veri numerik hale geldi. Sıkıntı şurada başlıyor:

### bu değişkenlerin değerleri arasında sayısal fark olduğu için yani 0 ın yoğunluk kat sayısı ile 3 ün yoğunluk katsayısı aynı olmadığından , değeri yüksek olan değişken türü baskın olup sonucu değiştirecektir.

### Burada One Hot Encoding araya giriyor

## One-Hot Dönüşümü

In [72]:
df_one_hot = pd.get_dummies(df,columns=["day"],dtype=int)

In [73]:
df_one_hot

total_bill   tip     sex smoker    time  size  yeni_cinsiyet  yeni_day   
0         16.99  1.01  Female     No  Dinner     2              0         1  \
1         10.34  1.66    Male     No  Dinner     3              1         1   
2         21.01  3.50    Male     No  Dinner     3              1         1   
3         23.68  3.31    Male     No  Dinner     2              1         1   
4         24.59  3.61  Female     No  Dinner     4              0         1   
..          ...   ...     ...    ...     ...   ...            ...       ...   
239       29.03  5.92    Male     No  Dinner     3              1         0   
240       27.18  2.00  Female    Yes  Dinner     2              0         0   
241       22.67  2.00    Male    Yes  Dinner     2              1         0   
242       17.82  1.75    Male     No  Dinner     2              1         0   
243       18.78  3.00  Female     No  Dinner     2              0         0   

     day_Thur  day_Fri  day_Sat  day_Sun  
0           0        0        0        1  
1           0        0        0        1  
2           0        0        0        1  
3           0        0        0        1  
4           0        0        0        1  
..        ...      ...      ...      ...  
239         0        0        1        0  
240         0        0        1        0  
241         0        0        1        0  
242         0        0        1        0  
243         1        0        0        0  

[244 rows x 12 columns]

### dikkat edilmesi gereken husus , örneğin cinsiyet ya erkektir ya kadın bu durumda onehotencoding yapılınca 2 değişken yaratılıyor ancak 1 değişken fazladan yaratılıyor. bunlara dikkat edilmesi gerekir